export const settings = {
  // DIRECTORY CONFIGS
  BASE_ROOT_DIRECTORY: '\\\\LUXE_BACKUP\\Luxe Files\\_Disenos',
  FOLDERS_STRUCTURE: [
    'Admon',
    'Arte Final',
    'Cut',
    'Editables',
    'Materiales',
    'Preview',
    'Print',
    'Resultado',
  ],
};

// ODOO STAGES IDS
export const STAGES_IDS = {
  ACTIVE: -2,
  IN_PROGRESS: -1,
  REQUEST: 1,
  QUOTATION: 2,
  QUOTATION_SENT: 3,
  WON: 4,
  ON_HOLD: 13,
  ANTICIPO: 8,
  PROPOSITION: 9,
  PROPOSITION_SENT: 34,
  ADJUSTMENT_1: 28,
  ADJUSTMENT_2: 29,
  ADJUSTMENT_FINAL: 30,
  APROVED_BY_CLIENT: 35,
  PRODUCTION: 10,
  INSTALLATION: 5,
  FINISHED: 6,
  SERVICE_CALLS: 11,
  COBRADO: 7,
  DESIGN: 27,
};

export const ARTIFICIAL_STAGES_FILTERS = {
  ACTIVE: [
    STAGES_IDS.REQUEST,
    STAGES_IDS.QUOTATION,
    STAGES_IDS.QUOTATION_SENT,
    STAGES_IDS.WON,
    STAGES_IDS.ANTICIPO,
    STAGES_IDS.PROPOSITION,
    STAGES_IDS.PROPOSITION_SENT,
    STAGES_IDS.ADJUSTMENT_1,
    STAGES_IDS.ADJUSTMENT_2,
    STAGES_IDS.ADJUSTMENT_FINAL,
    STAGES_IDS.APROVED_BY_CLIENT,
    STAGES_IDS.DESIGN,
    STAGES_IDS.PRODUCTION,
    STAGES_IDS.INSTALLATION,
  ],
  IN_PROGRESS: [
    STAGES_IDS.DESIGN,
    STAGES_IDS.ADJUSTMENT_1,
    STAGES_IDS.ADJUSTMENT_2,
    STAGES_IDS.ADJUSTMENT_FINAL,
    STAGES_IDS.APROVED_BY_CLIENT,
    STAGES_IDS.PRODUCTION,
    //STAGES_IDS.INSTALLATION,
  ],
};

// ODOO STAGE FIELD ID
export const STAGE_FIELD_ID = 9133; // ID of the message related to stage field

export const STAGESIDSALLOWEDTODOAPROPOSAL = [
  STAGES_IDS.DESIGN, //Design
  STAGES_IDS.ADJUSTMENT_1, //First Adjustment
  STAGES_IDS.ADJUSTMENT_2, //Second Adjustment
  STAGES_IDS.ADJUSTMENT_FINAL, //Final Adjustment
];

export const ROLES_IDS = {
  ADMIN: 1,
  DESIGNER: 2,
  TECHNICIAN: 3,
};

export const SUPPORTED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp'];

export const SERVER_FRONTEND = 'http://localhost:4000';
